name: groshop
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  percent_indicator: ^4.0.0
  flutter_rating_bar: ^4.0.0
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^8.0.1
  grouped_buttons:
    git:
      url: https://github.com/xyzbilal/grouped_buttons.git
      ref: master
  provider: ^6.0.2
  carousel_slider: ^4.0.0
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  firebase_analytics: ^9.1.4
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.13
  firebase_crashlytics: ^2.6.1
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.0
  scoped_model: ^2.0.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  fonts:
     - family: ProductSans
       fonts:
         - asset: fonts/ProductSans-Regular.ttf
         - asset: fonts/ProductSans-Bold.ttf


  assets:
    - assets/
    - assets/ProductImages/
    - assets/PaymentIcons/
    - assets/CategoryImages/
    - assets/HomeBanner/
    - assets/StoreImages/

